version: '3.8'

services:
  webbridgebot:
    image: mshafiee/webbridgebot
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - BASE_URL=${BASE_URL}
      - PORT=${PORT}
      - HASH_LENGTH=${HASH_LENGTH}
      - MAX_CACHE_SIZE=${MAX_CACHE_SIZE}
      - LOG_CHANNEL_ID=${LOG_CHANNEL_ID}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .cache:/app/.cache  # Persist .cache data between container restarts
